### ISSUE TITLE
The Limitations of Storing User Information in Comments or Posts

### ISSUE THREAD

**Issue by AmBplus** [thisisnabi/Blogger#41]
Hello, one thing bothers me, if we are in a context where users can login, then the user's name or other information may change, which happens when the post or the author himself is posted, what I saw Strangely, this information is stored inside the comment itself, or it is written inside the work itself, for example, an author may later change his last name and want to edit his information, but it is not possible in this way, or the normal user himself may want to change his information later. Granted, this is more useful where the data isn't going to change at all, so it looks incomplete.

**Comment by thisisnabi** [comment]
Hello, the user does not login the site to comment.
The user is not supposed to edit her/his information.

According to Business, the user enters his name  along with his email when registering a comment. 
![image](https://github.com/thisisnabi/Blogger/assets/3371886/5c768d1d-9e87-4733-b869-c3ac2da4f39a)

According to the entered specifications, all the information of a user can be a VO.
Perhaps you want to consider the `user` as an entity.
But here we don't want to do that, because user uniqueness doesn't add anything to us.
I have a guest who wants to comment. The nature of the guest is of interest to me [Name & Email].

**Comment by AmBplus** [comment]
As I said, this design is not a problem when no information is going to be changed, and users are always registered as guests, which may be good for the educational aspect, but in some sites such as virgool.io , this design does not work and needs to be modified.
